name: release-plugin
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - ".github/**"
      - "README.md"
      - "LICENSE"
    branches:
      - master

jobs:
  release-plugin:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Versioning
        uses: ./.github/actions/version
      - name: Package Plugin - 4.26
        uses: ./.github/actions/package
        with:
          engineVersion: "4.26"
          releaseVersion: ${{ steps.gitversion.outputs.semVer }}
          epicGamesDirectory: ${{ secrets.EPIC_GAMES_DIRECTORY }}
          launcherDirectory: ${{ secrets.LAUNCHER_DIRECTORY }}
      - name: Package Plugin - 4.27
        uses: ./.github/actions/package
        with:
          engineVersion: "4.27"
          releaseVersion: ${{ steps.gitversion.outputs.semVer }}
          epicGamesDirectory: ${{ secrets.EPIC_GAMES_DIRECTORY }}
          launcherDirectory: ${{ secrets.LAUNCHER_DIRECTORY }}
      - name: Package Plugin - 5.0
        uses: ./.github/actions/package
        with:
          engineVersion: "5.0"
          releaseVersion: ${{ steps.gitversion.outputs.semVer }}
          epicGamesDirectory: ${{ secrets.EPIC_GAMES_DIRECTORY }}
          launcherDirectory: ${{ secrets.LAUNCHER_DIRECTORY }}
      - name: Package Plugin - 5.1
        uses: ./.github/actions/package
        with:
          engineVersion: "5.1"
          releaseVersion: ${{ steps.gitversion.outputs.semVer }}
          epicGamesDirectory: ${{ secrets.EPIC_GAMES_DIRECTORY }}
          launcherDirectory: ${{ secrets.LAUNCHER_DIRECTORY }}
      - name: Create Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          artifacts: "${{ runner.temp }}/output/*.zip"
          tag: ${{ env.GitVersion_SemVer }}
          commit: ${{ github.sha }}
          prerelease: ${{ github.ref != 'refs/heads/master' }}
